databases:
  - name: tidybudget
    databaseName: tidybudget
    user: postgres

services:
  - type: web
    name: tidybudget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tidybudget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
